Repository h3js/h3, pull requests merged in 2023-08, with the labels that each got.

#487 docs: fix `deleteCookie` description
  src/utils/cookie.ts
Labels: ready

#485 feat: object-syntax event handlers
  src/event/utils.ts
  src/types.ts
  test/types.test-d.ts
Labels: enhancement

#494 feat: support react pipeable streams
  package.json
  pnpm-lock.yaml
  src/utils/response.ts
  test/integrations.test.ts
Labels: enhancement, stream
