Repository h3js/h3, pull requests merged in 2023-07, with the labels that each got.

#428 docs: split readme into subsection and document missing helpers
  README.md
Labels: documentation, helpers

#429 feat: add `event.method` and `event.headers`
  src/event/event.ts
  test/event.test.ts
Labels: enhancement, events-api, ready

#422 feat: support blob responses
  src/app.ts
  test/app.test.ts
Labels: enhancement, proxy, ready

#207 feat(readBody): validate requests with `application/json` content type
  src/utils/body.ts
  test/body.test.ts
Labels: enhancement

#445 fix: split `set-cookie` value when handling web responses
  src/utils/response.ts
Labels: enhancement, ready

#441 fix(proxy): respect `fetchOptions.method` over incoming request method
  src/utils/proxy.ts
Labels: proxy

#453 fix: append `set-cookie` headers in web reponse
  src/utils/response.ts
Labels: bug, webstd

#421 feat: add `readFormData` util
  src/utils/body.ts
  test/utils.test.ts
Labels: enhancement, ready

#440 fix(proxy): avoid decoding request body as utf8
  src/utils/proxy.ts
  test/assets/dummy.pdf
  test/proxy.test.ts
Labels: enhancement, proxy

#416 fix(readMultipartFormData): handle utf8 encoding for `name` and `filename`
  src/utils/internal/multipart.ts
  test/body.test.ts
Labels: bug

#427 feat: add `removeResponseHeader` and `clearResponseHeaders` utils
  src/utils/response.ts
  test/header.test.ts
Labels: enhancement, helpers, ready

#417 feat: add event handler generics for typed request body and query
  .github/workflows/ci.yml
  .gitignore
  package.json
  src/event/event.ts
  src/event/utils.ts
  src/types.ts
  src/utils/body.ts
  src/utils/request.ts
  test/types.test-d.ts
  tsconfig.json
Labels: enhancement, pending

#468 docs: improve nightly release usage section
  README.md
Labels: documentation, ready
